version: 2
jobs:
  build:

    working_directory: ~/string-calculator-12

    docker:
      - image: circleci/openjdk:11-stretch

    steps:

      - checkout

      - restore_cache:
          key: string-calculator-12-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: string-calculator-12-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/string-calculator-12-1.0-SNAPSHOT.jar
